# AppVeyor documentation https://www.appveyor.com/docs

version: '{build}'

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish for pull requests
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1

test: off

artifacts:
# Store VSIX packages
- path: .\Artifacts\**\*.vsix
  name: VSIX
# Store xUnit Test Results
- path: .\Artifacts\**\*.xml
  name: xUnit Test Results

deploy:
# Publish VSIX packages
- provider: NuGet
  server: https://www.myget.org/F/aspnet-mvc-boilerplate/vsix/
  api_key:
    secure: aunGGWt32irQiOTX2wIO6e2Y5Ga0girA3xSUsmQv6E9d6ohHdbK5HJpXpmxW9QM3
  on:
    # Only publish from the master branch
    branch: master
  # Publish the following file
  artifact: VSIX